[production]
phpSettings.display_startup_errors = 0
phpSettings.display_errors = 0

# db設定
resources.db.adapter = "pdo_mysql"
resources.db.params.host = "db"
resources.db.params.charset = "utf8mb4"
resources.db.params.port = 3306
resources.db.params.username = "todo_user"
resources.db.params.password = "todo_password"
resources.db.params.dbname = "todo_app"
resources.db.params.unix_socket = "/var/run/mysqld/mysqld.sock"

bootstrap.path = APPLICATION_PATH "/Bootstrap.php"
bootstrap.class = "Bootstrap"
resources.frontController.controllerDirectory = APPLICATION_PATH "/controllers"

[development : production]
phpSettings.display_startup_errors = 1
phpSettings.display_errors = 1
