<h1 class="text-lg">Add New Todo</h1>

<div class="mt-2">
  <form action="/todo/add" method="post" class="max-w-sm mr-auto">
    <div class="mb-5">
      <label for="title" class="block mb-2 text-sm font-medium text-gray-900">Title</label>
      <input type="text" id="title" name="title" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" required />
    </div>
    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full px-5 py-2.5 text-center">Add Todo</button>
  </form>

</div>
